# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created: Wed Nov 12 11:56:56 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(426, 263)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.generalTab = QtGui.QWidget()
        self.generalTab.setObjectName("generalTab")
        self.formLayout = QtGui.QFormLayout(self.generalTab)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(self.generalTab)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.startupContext = QtGui.QComboBox(self.generalTab)
        self.startupContext.setObjectName("startupContext")
        self.startupContext.addItem("")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.startupContext)
        self.label_2 = QtGui.QLabel(self.generalTab)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.dateFormat = QtGui.QLineEdit(self.generalTab)
        self.dateFormat.setObjectName("dateFormat")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.dateFormat)
        self.label_3 = QtGui.QLabel(self.generalTab)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_3)
        self.confirmExit = QtGui.QCheckBox(self.generalTab)
        self.confirmExit.setChecked(True)
        self.confirmExit.setObjectName("confirmExit")
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.confirmExit)
        self.label_7 = QtGui.QLabel(self.generalTab)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_7)
        self.defaultDueTimeOn = QtGui.QCheckBox(self.generalTab)
        self.defaultDueTimeOn.setChecked(True)
        self.defaultDueTimeOn.setObjectName("defaultDueTimeOn")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.defaultDueTimeOn)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.defaultDueTimeSpin = QtGui.QSpinBox(self.generalTab)
        self.defaultDueTimeSpin.setMaximumSize(QtCore.QSize(35, 16777215))
        self.defaultDueTimeSpin.setProperty("value", 24)
        self.defaultDueTimeSpin.setObjectName("defaultDueTimeSpin")
        self.horizontalLayout.addWidget(self.defaultDueTimeSpin)
        self.defaultDueTimeUnit = QtGui.QComboBox(self.generalTab)
        self.defaultDueTimeUnit.setMaximumSize(QtCore.QSize(60, 16777215))
        self.defaultDueTimeUnit.setObjectName("defaultDueTimeUnit")
        self.defaultDueTimeUnit.addItem("")
        self.defaultDueTimeUnit.addItem("")
        self.horizontalLayout.addWidget(self.defaultDueTimeUnit)
        self.label_8 = QtGui.QLabel(self.generalTab)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.formLayout.setLayout(4, QtGui.QFormLayout.FieldRole, self.horizontalLayout)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout.setItem(5, QtGui.QFormLayout.LabelRole, spacerItem)
        self.tabWidget.addTab(self.generalTab, "")
        self.notificationsTab = QtGui.QWidget()
        self.notificationsTab.setObjectName("notificationsTab")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.notificationsTab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.notificationsOn = QtGui.QCheckBox(self.notificationsTab)
        self.notificationsOn.setChecked(True)
        self.notificationsOn.setObjectName("notificationsOn")
        self.gridLayout_2.addWidget(self.notificationsOn, 0, 0, 1, 1)
        self.notificationsCurrentContext = QtGui.QCheckBox(self.notificationsTab)
        self.notificationsCurrentContext.setChecked(True)
        self.notificationsCurrentContext.setObjectName("notificationsCurrentContext")
        self.gridLayout_2.addWidget(self.notificationsCurrentContext, 1, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtGui.QLabel(self.notificationsTab)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.notificationsTab)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.notifyIntervalSpin = QtGui.QSpinBox(self.notificationsTab)
        self.notifyIntervalSpin.setMaximumSize(QtCore.QSize(40, 16777215))
        self.notifyIntervalSpin.setMaximum(60)
        self.notifyIntervalSpin.setProperty("value", 30)
        self.notifyIntervalSpin.setObjectName("notifyIntervalSpin")
        self.gridLayout.addWidget(self.notifyIntervalSpin, 1, 1, 1, 1)
        self.notifyTimeUnit = QtGui.QComboBox(self.notificationsTab)
        self.notifyTimeUnit.setMaximumSize(QtCore.QSize(70, 16777215))
        self.notifyTimeUnit.setObjectName("notifyTimeUnit")
        self.notifyTimeUnit.addItem("")
        self.notifyTimeUnit.addItem("")
        self.gridLayout.addWidget(self.notifyTimeUnit, 0, 2, 1, 1)
        self.notifyTimeSpin = QtGui.QSpinBox(self.notificationsTab)
        self.notifyTimeSpin.setMaximumSize(QtCore.QSize(40, 16777215))
        self.notifyTimeSpin.setProperty("value", 6)
        self.notifyTimeSpin.setObjectName("notifyTimeSpin")
        self.gridLayout.addWidget(self.notifyTimeSpin, 0, 1, 1, 1)
        self.notifyIntervalUnit = QtGui.QComboBox(self.notificationsTab)
        self.notifyIntervalUnit.setMaximumSize(QtCore.QSize(70, 16777215))
        self.notifyIntervalUnit.setObjectName("notifyIntervalUnit")
        self.notifyIntervalUnit.addItem("")
        self.notifyIntervalUnit.addItem("")
        self.gridLayout.addWidget(self.notifyIntervalUnit, 1, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.tabWidget.addTab(self.notificationsTab, "")
        self.themeTab = QtGui.QWidget()
        self.themeTab.setObjectName("themeTab")
        self.tabWidget.addTab(self.themeTab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        self.notifyIntervalUnit.setCurrentIndex(1)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "workload settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Startup context", None, QtGui.QApplication.UnicodeUTF8))
        self.startupContext.setItemText(0, QtGui.QApplication.translate("Dialog", "Last opened", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Date and time format", None, QtGui.QApplication.UnicodeUTF8))
        self.dateFormat.setText(QtGui.QApplication.translate("Dialog", "%d-%m-%Y %H:%M", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "On program exit", None, QtGui.QApplication.UnicodeUTF8))
        self.confirmExit.setText(QtGui.QApplication.translate("Dialog", "Confirm exit", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "New tasks:", None, QtGui.QApplication.UnicodeUTF8))
        self.defaultDueTimeOn.setText(QtGui.QApplication.translate("Dialog", "Set default due date/time", None, QtGui.QApplication.UnicodeUTF8))
        self.defaultDueTimeUnit.setItemText(0, QtGui.QApplication.translate("Dialog", "Hour(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.defaultDueTimeUnit.setItemText(1, QtGui.QApplication.translate("Dialog", "Day(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", " after create time", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.generalTab), QtGui.QApplication.translate("Dialog", "General", None, QtGui.QApplication.UnicodeUTF8))
        self.notificationsOn.setText(QtGui.QApplication.translate("Dialog", "Show notifications", None, QtGui.QApplication.UnicodeUTF8))
        self.notificationsCurrentContext.setText(QtGui.QApplication.translate("Dialog", "Only from current context", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Repeat notification every:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Notify about ending task (before task end):", None, QtGui.QApplication.UnicodeUTF8))
        self.notifyTimeUnit.setItemText(0, QtGui.QApplication.translate("Dialog", "Hour(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.notifyTimeUnit.setItemText(1, QtGui.QApplication.translate("Dialog", "Minute(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.notifyIntervalUnit.setItemText(0, QtGui.QApplication.translate("Dialog", "Hour(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.notifyIntervalUnit.setItemText(1, QtGui.QApplication.translate("Dialog", "Minute(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.notificationsTab), QtGui.QApplication.translate("Dialog", "Notifications", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.themeTab), QtGui.QApplication.translate("Dialog", "Theme", None, QtGui.QApplication.UnicodeUTF8))

