# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created: Mon Dec  1 17:58:38 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.WindowModal)
        Dialog.resize(618, 430)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Serif")
        Dialog.setFont(font)
        Dialog.setModal(False)
        self.gridLayout_4 = QtGui.QGridLayout(Dialog)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_4.addWidget(self.buttonBox, 1, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setElideMode(QtCore.Qt.ElideRight)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.generalTab = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.generalTab.sizePolicy().hasHeightForWidth())
        self.generalTab.setSizePolicy(sizePolicy)
        self.generalTab.setMinimumSize(QtCore.QSize(60, 0))
        self.generalTab.setObjectName("generalTab")
        self.formLayout = QtGui.QFormLayout(self.generalTab)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(self.generalTab)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.startupContext = QtGui.QComboBox(self.generalTab)
        self.startupContext.setMaximumSize(QtCore.QSize(150, 16777215))
        self.startupContext.setObjectName("startupContext")
        self.startupContext.addItem("")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.startupContext)
        self.label_2 = QtGui.QLabel(self.generalTab)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.dateFormat = QtGui.QLineEdit(self.generalTab)
        self.dateFormat.setMaximumSize(QtCore.QSize(150, 16777215))
        self.dateFormat.setObjectName("dateFormat")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.dateFormat)
        self.label_7 = QtGui.QLabel(self.generalTab)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_7)
        self.defaultDueTimeOn = QtGui.QCheckBox(self.generalTab)
        self.defaultDueTimeOn.setChecked(True)
        self.defaultDueTimeOn.setObjectName("defaultDueTimeOn")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.defaultDueTimeOn)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.defaultDueTimeSpin = QtGui.QSpinBox(self.generalTab)
        self.defaultDueTimeSpin.setMinimumSize(QtCore.QSize(40, 0))
        self.defaultDueTimeSpin.setMaximumSize(QtCore.QSize(40, 16777215))
        self.defaultDueTimeSpin.setProperty("value", 24)
        self.defaultDueTimeSpin.setObjectName("defaultDueTimeSpin")
        self.horizontalLayout.addWidget(self.defaultDueTimeSpin)
        self.defaultDueTimeUnit = QtGui.QComboBox(self.generalTab)
        self.defaultDueTimeUnit.setMaximumSize(QtCore.QSize(60, 16777215))
        self.defaultDueTimeUnit.setObjectName("defaultDueTimeUnit")
        self.defaultDueTimeUnit.addItem("")
        self.defaultDueTimeUnit.addItem("")
        self.horizontalLayout.addWidget(self.defaultDueTimeUnit)
        self.label_8 = QtGui.QLabel(self.generalTab)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.formLayout.setLayout(4, QtGui.QFormLayout.FieldRole, self.horizontalLayout)
        self.label_24 = QtGui.QLabel(self.generalTab)
        self.label_24.setObjectName("label_24")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_24)
        self.language = QtGui.QComboBox(self.generalTab)
        self.language.setMaximumSize(QtCore.QSize(150, 16777215))
        self.language.setObjectName("language")
        self.language.addItem("")
        self.language.addItem("")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.language)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout.setItem(6, QtGui.QFormLayout.LabelRole, spacerItem)
        self.label_3 = QtGui.QLabel(self.generalTab)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_3)
        self.confirmExit = QtGui.QCheckBox(self.generalTab)
        self.confirmExit.setChecked(True)
        self.confirmExit.setObjectName("confirmExit")
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.confirmExit)
        self.tabWidget.addTab(self.generalTab, "")
        self.notificationsTab = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.notificationsTab.sizePolicy().hasHeightForWidth())
        self.notificationsTab.setSizePolicy(sizePolicy)
        self.notificationsTab.setMinimumSize(QtCore.QSize(60, 0))
        self.notificationsTab.setObjectName("notificationsTab")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.notificationsTab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.notificationsOn = QtGui.QCheckBox(self.notificationsTab)
        self.notificationsOn.setChecked(True)
        self.notificationsOn.setObjectName("notificationsOn")
        self.gridLayout_2.addWidget(self.notificationsOn, 0, 0, 1, 1)
        self.notificationsCurrentContext = QtGui.QCheckBox(self.notificationsTab)
        self.notificationsCurrentContext.setChecked(True)
        self.notificationsCurrentContext.setObjectName("notificationsCurrentContext")
        self.gridLayout_2.addWidget(self.notificationsCurrentContext, 1, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtGui.QLabel(self.notificationsTab)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.notificationsTab)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.notifyIntervalSpin = QtGui.QSpinBox(self.notificationsTab)
        self.notifyIntervalSpin.setMinimumSize(QtCore.QSize(40, 0))
        self.notifyIntervalSpin.setMaximumSize(QtCore.QSize(40, 16777215))
        self.notifyIntervalSpin.setMaximum(60)
        self.notifyIntervalSpin.setProperty("value", 30)
        self.notifyIntervalSpin.setObjectName("notifyIntervalSpin")
        self.gridLayout.addWidget(self.notifyIntervalSpin, 1, 1, 1, 1)
        self.notifyTimeUnit = QtGui.QComboBox(self.notificationsTab)
        self.notifyTimeUnit.setMaximumSize(QtCore.QSize(70, 16777215))
        self.notifyTimeUnit.setObjectName("notifyTimeUnit")
        self.notifyTimeUnit.addItem("")
        self.notifyTimeUnit.addItem("")
        self.gridLayout.addWidget(self.notifyTimeUnit, 0, 2, 1, 1)
        self.notifyTimeSpin = QtGui.QSpinBox(self.notificationsTab)
        self.notifyTimeSpin.setMinimumSize(QtCore.QSize(40, 0))
        self.notifyTimeSpin.setMaximumSize(QtCore.QSize(40, 16777215))
        self.notifyTimeSpin.setProperty("value", 6)
        self.notifyTimeSpin.setObjectName("notifyTimeSpin")
        self.gridLayout.addWidget(self.notifyTimeSpin, 0, 1, 1, 1)
        self.notifyIntervalUnit = QtGui.QComboBox(self.notificationsTab)
        self.notifyIntervalUnit.setMaximumSize(QtCore.QSize(70, 16777215))
        self.notifyIntervalUnit.setObjectName("notifyIntervalUnit")
        self.notifyIntervalUnit.addItem("")
        self.notifyIntervalUnit.addItem("")
        self.gridLayout.addWidget(self.notifyIntervalUnit, 1, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.tabWidget.addTab(self.notificationsTab, "")
        self.fontsTab = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fontsTab.sizePolicy().hasHeightForWidth())
        self.fontsTab.setSizePolicy(sizePolicy)
        self.fontsTab.setMinimumSize(QtCore.QSize(60, 0))
        self.fontsTab.setObjectName("fontsTab")
        self.gridLayout_5 = QtGui.QGridLayout(self.fontsTab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.allFonts = QtGui.QListWidget(self.fontsTab)
        self.allFonts.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.allFonts.setObjectName("allFonts")
        self.horizontalLayout_12.addWidget(self.allFonts)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setContentsMargins(3, -1, 3, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.addFonts = QtGui.QPushButton(self.fontsTab)
        self.addFonts.setMaximumSize(QtCore.QSize(14, 50))
        self.addFonts.setObjectName("addFonts")
        self.verticalLayout.addWidget(self.addFonts)
        self.removeFonts = QtGui.QPushButton(self.fontsTab)
        self.removeFonts.setMaximumSize(QtCore.QSize(14, 50))
        self.removeFonts.setObjectName("removeFonts")
        self.verticalLayout.addWidget(self.removeFonts)
        self.horizontalLayout_12.addLayout(self.verticalLayout)
        self.chosenFonts = QtGui.QListWidget(self.fontsTab)
        self.chosenFonts.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.chosenFonts.setObjectName("chosenFonts")
        self.horizontalLayout_12.addWidget(self.chosenFonts)
        self.gridLayout_5.addLayout(self.horizontalLayout_12, 1, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.fontsTab)
        self.label_13.setObjectName("label_13")
        self.gridLayout_5.addWidget(self.label_13, 0, 0, 1, 1)
        self.tabWidget.addTab(self.fontsTab, "")
        self.themeTab = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.themeTab.sizePolicy().hasHeightForWidth())
        self.themeTab.setSizePolicy(sizePolicy)
        self.themeTab.setMinimumSize(QtCore.QSize(60, 0))
        self.themeTab.setObjectName("themeTab")
        self.gridLayout_3 = QtGui.QGridLayout(self.themeTab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtGui.QLabel(self.themeTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(230, 24))
        self.label_6.setMaximumSize(QtCore.QSize(0, 16777215))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.windowBG = QtGui.QPushButton(self.themeTab)
        self.windowBG.setMaximumSize(QtCore.QSize(20, 20))
        self.windowBG.setAutoFillBackground(True)
        self.windowBG.setText("")
        self.windowBG.setFlat(False)
        self.windowBG.setObjectName("windowBG")
        self.horizontalLayout_3.addWidget(self.windowBG)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_18 = QtGui.QLabel(self.themeTab)
        self.label_18.setMinimumSize(QtCore.QSize(145, 24))
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_11.addWidget(self.label_18)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem1)
        self.windowOpacity = QtGui.QSpinBox(self.themeTab)
        self.windowOpacity.setMinimumSize(QtCore.QSize(40, 0))
        self.windowOpacity.setMaximumSize(QtCore.QSize(40, 16777215))
        self.windowOpacity.setMaximum(100)
        self.windowOpacity.setSingleStep(5)
        self.windowOpacity.setProperty("value", 90)
        self.windowOpacity.setObjectName("windowOpacity")
        self.horizontalLayout_11.addWidget(self.windowOpacity)
        self.gridLayout_3.addLayout(self.horizontalLayout_11, 0, 1, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_9 = QtGui.QLabel(self.themeTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(230, 24))
        self.label_9.setMaximumSize(QtCore.QSize(0, 16777215))
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        self.windowFrame = QtGui.QPushButton(self.themeTab)
        self.windowFrame.setMaximumSize(QtCore.QSize(20, 20))
        self.windowFrame.setAutoFillBackground(True)
        self.windowFrame.setText("")
        self.windowFrame.setFlat(False)
        self.windowFrame.setObjectName("windowFrame")
        self.horizontalLayout_4.addWidget(self.windowFrame)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_16 = QtGui.QLabel(self.themeTab)
        self.label_16.setMinimumSize(QtCore.QSize(145, 24))
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_8.addWidget(self.label_16)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.taskEditorOpacity = QtGui.QSpinBox(self.themeTab)
        self.taskEditorOpacity.setMinimumSize(QtCore.QSize(40, 0))
        self.taskEditorOpacity.setMaximumSize(QtCore.QSize(40, 16777215))
        self.taskEditorOpacity.setMaximum(100)
        self.taskEditorOpacity.setSingleStep(5)
        self.taskEditorOpacity.setProperty("value", 90)
        self.taskEditorOpacity.setObjectName("taskEditorOpacity")
        self.horizontalLayout_8.addWidget(self.taskEditorOpacity)
        self.gridLayout_3.addLayout(self.horizontalLayout_8, 1, 1, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_11 = QtGui.QLabel(self.themeTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QtCore.QSize(230, 24))
        self.label_11.setMaximumSize(QtCore.QSize(0, 16777215))
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_6.addWidget(self.label_11)
        self.tasklistFrame = QtGui.QPushButton(self.themeTab)
        self.tasklistFrame.setMaximumSize(QtCore.QSize(20, 20))
        self.tasklistFrame.setAutoFillBackground(True)
        self.tasklistFrame.setText("")
        self.tasklistFrame.setFlat(False)
        self.tasklistFrame.setObjectName("tasklistFrame")
        self.horizontalLayout_6.addWidget(self.tasklistFrame)
        self.gridLayout_3.addLayout(self.horizontalLayout_6, 2, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_10 = QtGui.QLabel(self.themeTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(230, 24))
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_5.addWidget(self.label_10)
        self.tasklistBG = QtGui.QPushButton(self.themeTab)
        self.tasklistBG.setMaximumSize(QtCore.QSize(20, 20))
        self.tasklistBG.setAutoFillBackground(True)
        self.tasklistBG.setText("")
        self.tasklistBG.setFlat(False)
        self.tasklistBG.setObjectName("tasklistBG")
        self.horizontalLayout_5.addWidget(self.tasklistBG)
        self.gridLayout_3.addLayout(self.horizontalLayout_5, 3, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_12 = QtGui.QLabel(self.themeTab)
        self.label_12.setMinimumSize(QtCore.QSize(90, 24))
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_2.addWidget(self.label_12)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.fontFamily = QtGui.QComboBox(self.themeTab)
        self.fontFamily.setMinimumSize(QtCore.QSize(170, 0))
        self.fontFamily.setFrame(True)
        self.fontFamily.setObjectName("fontFamily")
        self.horizontalLayout_2.addWidget(self.fontFamily)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 3, 1, 1, 1)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_23 = QtGui.QLabel(self.themeTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setMinimumSize(QtCore.QSize(230, 24))
        self.label_23.setMaximumSize(QtCore.QSize(0, 16777215))
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_16.addWidget(self.label_23)
        self.alternateTasklistBG = QtGui.QPushButton(self.themeTab)
        self.alternateTasklistBG.setMaximumSize(QtCore.QSize(20, 20))
        self.alternateTasklistBG.setAutoFillBackground(True)
        self.alternateTasklistBG.setText("")
        self.alternateTasklistBG.setFlat(False)
        self.alternateTasklistBG.setObjectName("alternateTasklistBG")
        self.horizontalLayout_16.addWidget(self.alternateTasklistBG)
        self.gridLayout_3.addLayout(self.horizontalLayout_16, 4, 0, 1, 1)
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_15 = QtGui.QLabel(self.themeTab)
        self.label_15.setMinimumSize(QtCore.QSize(145, 24))
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_25.addWidget(self.label_15)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem4)
        self.fontSize = QtGui.QSpinBox(self.themeTab)
        self.fontSize.setMinimumSize(QtCore.QSize(40, 0))
        self.fontSize.setMaximumSize(QtCore.QSize(40, 16777215))
        self.fontSize.setMinimum(8)
        self.fontSize.setMaximum(16)
        self.fontSize.setProperty("value", 10)
        self.fontSize.setObjectName("fontSize")
        self.horizontalLayout_25.addWidget(self.fontSize)
        self.gridLayout_3.addLayout(self.horizontalLayout_25, 4, 1, 1, 1)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_14 = QtGui.QLabel(self.themeTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setMinimumSize(QtCore.QSize(230, 24))
        self.label_14.setMaximumSize(QtCore.QSize(0, 16777215))
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_10.addWidget(self.label_14)
        self.taskEditorBG = QtGui.QPushButton(self.themeTab)
        self.taskEditorBG.setMaximumSize(QtCore.QSize(20, 20))
        self.taskEditorBG.setAutoFillBackground(True)
        self.taskEditorBG.setText("")
        self.taskEditorBG.setFlat(False)
        self.taskEditorBG.setObjectName("taskEditorBG")
        self.horizontalLayout_10.addWidget(self.taskEditorBG)
        self.gridLayout_3.addLayout(self.horizontalLayout_10, 5, 0, 1, 1)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_20 = QtGui.QLabel(self.themeTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setMinimumSize(QtCore.QSize(145, 24))
        self.label_20.setMaximumSize(QtCore.QSize(0, 16777215))
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_20.addWidget(self.label_20)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem5)
        self.workloadFontColor = QtGui.QPushButton(self.themeTab)
        self.workloadFontColor.setMaximumSize(QtCore.QSize(20, 20))
        self.workloadFontColor.setAutoFillBackground(True)
        self.workloadFontColor.setText("")
        self.workloadFontColor.setFlat(False)
        self.workloadFontColor.setObjectName("workloadFontColor")
        self.horizontalLayout_20.addWidget(self.workloadFontColor)
        self.gridLayout_3.addLayout(self.horizontalLayout_20, 5, 1, 1, 1)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_21 = QtGui.QLabel(self.themeTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setMinimumSize(QtCore.QSize(230, 24))
        self.label_21.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_14.addWidget(self.label_21)
        self.taskEditorFrame = QtGui.QPushButton(self.themeTab)
        self.taskEditorFrame.setMaximumSize(QtCore.QSize(20, 20))
        self.taskEditorFrame.setAutoFillBackground(True)
        self.taskEditorFrame.setText("")
        self.taskEditorFrame.setFlat(False)
        self.taskEditorFrame.setObjectName("taskEditorFrame")
        self.horizontalLayout_14.addWidget(self.taskEditorFrame)
        self.gridLayout_3.addLayout(self.horizontalLayout_14, 6, 0, 1, 1)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_25 = QtGui.QLabel(self.themeTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        self.label_25.setMinimumSize(QtCore.QSize(230, 24))
        self.label_25.setMaximumSize(QtCore.QSize(0, 16777215))
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_18.addWidget(self.label_25)
        self.buttonBG = QtGui.QPushButton(self.themeTab)
        self.buttonBG.setMaximumSize(QtCore.QSize(20, 20))
        self.buttonBG.setAutoFillBackground(True)
        self.buttonBG.setText("")
        self.buttonBG.setFlat(False)
        self.buttonBG.setObjectName("buttonBG")
        self.horizontalLayout_18.addWidget(self.buttonBG)
        self.gridLayout_3.addLayout(self.horizontalLayout_18, 7, 0, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_17 = QtGui.QLabel(self.themeTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setMinimumSize(QtCore.QSize(145, 24))
        self.label_17.setMaximumSize(QtCore.QSize(0, 16777215))
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_7.addWidget(self.label_17)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem6)
        self.tasklistFontColor = QtGui.QPushButton(self.themeTab)
        self.tasklistFontColor.setMaximumSize(QtCore.QSize(20, 20))
        self.tasklistFontColor.setAutoFillBackground(True)
        self.tasklistFontColor.setText("")
        self.tasklistFontColor.setFlat(False)
        self.tasklistFontColor.setObjectName("tasklistFontColor")
        self.horizontalLayout_7.addWidget(self.tasklistFontColor)
        self.gridLayout_3.addLayout(self.horizontalLayout_7, 7, 1, 1, 1)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_22 = QtGui.QLabel(self.themeTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setMinimumSize(QtCore.QSize(230, 24))
        self.label_22.setMaximumSize(QtCore.QSize(0, 16777215))
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_15.addWidget(self.label_22)
        self.selectedItem = QtGui.QPushButton(self.themeTab)
        self.selectedItem.setMaximumSize(QtCore.QSize(20, 20))
        self.selectedItem.setAutoFillBackground(True)
        self.selectedItem.setText("")
        self.selectedItem.setFlat(False)
        self.selectedItem.setObjectName("selectedItem")
        self.horizontalLayout_15.addWidget(self.selectedItem)
        self.gridLayout_3.addLayout(self.horizontalLayout_15, 8, 0, 1, 1)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_26 = QtGui.QLabel(self.themeTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        self.label_26.setMinimumSize(QtCore.QSize(230, 24))
        self.label_26.setMaximumSize(QtCore.QSize(0, 16777215))
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_19.addWidget(self.label_26)
        self.textInputBG = QtGui.QPushButton(self.themeTab)
        self.textInputBG.setMaximumSize(QtCore.QSize(20, 20))
        self.textInputBG.setAutoFillBackground(True)
        self.textInputBG.setText("")
        self.textInputBG.setFlat(False)
        self.textInputBG.setObjectName("textInputBG")
        self.horizontalLayout_19.addWidget(self.textInputBG)
        self.gridLayout_3.addLayout(self.horizontalLayout_19, 9, 0, 1, 1)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem7)
        self.resetToDefaults = QtGui.QPushButton(self.themeTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resetToDefaults.sizePolicy().hasHeightForWidth())
        self.resetToDefaults.setSizePolicy(sizePolicy)
        self.resetToDefaults.setMinimumSize(QtCore.QSize(0, 0))
        self.resetToDefaults.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.resetToDefaults.setObjectName("resetToDefaults")
        self.horizontalLayout_13.addWidget(self.resetToDefaults)
        self.gridLayout_3.addLayout(self.horizontalLayout_13, 9, 1, 1, 1)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_31 = QtGui.QLabel(self.themeTab)
        self.label_31.setMinimumSize(QtCore.QSize(145, 24))
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_23.addWidget(self.label_31)
        self.tasklistFontSize = QtGui.QSpinBox(self.themeTab)
        self.tasklistFontSize.setMinimumSize(QtCore.QSize(40, 0))
        self.tasklistFontSize.setMaximumSize(QtCore.QSize(40, 16777215))
        self.tasklistFontSize.setMinimum(8)
        self.tasklistFontSize.setMaximum(16)
        self.tasklistFontSize.setProperty("value", 10)
        self.tasklistFontSize.setObjectName("tasklistFontSize")
        self.horizontalLayout_23.addWidget(self.tasklistFontSize)
        self.gridLayout_3.addLayout(self.horizontalLayout_23, 6, 1, 1, 1)
        self.tabWidget.addTab(self.themeTab, "")
        self.shortcutsTab = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shortcutsTab.sizePolicy().hasHeightForWidth())
        self.shortcutsTab.setSizePolicy(sizePolicy)
        self.shortcutsTab.setMinimumSize(QtCore.QSize(0, 0))
        self.shortcutsTab.setObjectName("shortcutsTab")
        self.gridLayout_7 = QtGui.QGridLayout(self.shortcutsTab)
        self.gridLayout_7.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_19 = QtGui.QLabel(self.shortcutsTab)
        self.label_19.setObjectName("label_19")
        self.gridLayout_7.addWidget(self.label_19, 0, 0, 1, 1)
        self.mainWindowToggleKey = QtGui.QLineEdit(self.shortcutsTab)
        self.mainWindowToggleKey.setCursor(QtCore.Qt.IBeamCursor)
        self.mainWindowToggleKey.setObjectName("mainWindowToggleKey")
        self.gridLayout_7.addWidget(self.mainWindowToggleKey, 0, 1, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem8, 1, 1, 1, 1)
        self.tabWidget.addTab(self.shortcutsTab, "")
        self.gridLayout_4.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        self.notifyIntervalUnit.setCurrentIndex(1)
        self.fontFamily.setCurrentIndex(-1)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "workload settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Startup context", None, QtGui.QApplication.UnicodeUTF8))
        self.startupContext.setItemText(0, QtGui.QApplication.translate("Dialog", "Last opened", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Date and time format", None, QtGui.QApplication.UnicodeUTF8))
        self.dateFormat.setText(QtGui.QApplication.translate("Dialog", "%d-%m-%Y %H:%M", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "New tasks:", None, QtGui.QApplication.UnicodeUTF8))
        self.defaultDueTimeOn.setText(QtGui.QApplication.translate("Dialog", "Set default due date/time", None, QtGui.QApplication.UnicodeUTF8))
        self.defaultDueTimeUnit.setItemText(0, QtGui.QApplication.translate("Dialog", "Hour(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.defaultDueTimeUnit.setItemText(1, QtGui.QApplication.translate("Dialog", "Day(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", " after create time", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("Dialog", "Program Language:", None, QtGui.QApplication.UnicodeUTF8))
        self.language.setItemText(0, QtGui.QApplication.translate("Dialog", "Auto", None, QtGui.QApplication.UnicodeUTF8))
        self.language.setItemText(1, QtGui.QApplication.translate("Dialog", "English", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "On program exit", None, QtGui.QApplication.UnicodeUTF8))
        self.confirmExit.setText(QtGui.QApplication.translate("Dialog", "Confirm exit", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.generalTab), QtGui.QApplication.translate("Dialog", " General ", None, QtGui.QApplication.UnicodeUTF8))
        self.notificationsOn.setText(QtGui.QApplication.translate("Dialog", "Show notifications", None, QtGui.QApplication.UnicodeUTF8))
        self.notificationsCurrentContext.setText(QtGui.QApplication.translate("Dialog", "Only from current context", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Repeat notification every:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Notify about ending task (before task end):", None, QtGui.QApplication.UnicodeUTF8))
        self.notifyTimeUnit.setItemText(0, QtGui.QApplication.translate("Dialog", "Hour(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.notifyTimeUnit.setItemText(1, QtGui.QApplication.translate("Dialog", "Minute(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.notifyIntervalUnit.setItemText(0, QtGui.QApplication.translate("Dialog", "Hour(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.notifyIntervalUnit.setItemText(1, QtGui.QApplication.translate("Dialog", "Minute(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.notificationsTab), QtGui.QApplication.translate("Dialog", " Notifications ", None, QtGui.QApplication.UnicodeUTF8))
        self.addFonts.setText(QtGui.QApplication.translate("Dialog", ">", None, QtGui.QApplication.UnicodeUTF8))
        self.removeFonts.setText(QtGui.QApplication.translate("Dialog", "<", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Dialog", "Select Fonts you would like to use in program", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.fontsTab), QtGui.QApplication.translate("Dialog", " Fonts ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Window background", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Dialog", "Main window opacity", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "Window frame", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Dialog", "Task editor opacity", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Dialog", "Tasklist frame", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog", "Tasklist background", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Dialog", "Workload Font", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("Dialog", "Alternate tasklist background", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Dialog", "Workload Font size", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Dialog", "Task editor Background", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("Dialog", "Workload font color", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("Dialog", "Task editor Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("Dialog", "Button and controls background", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Dialog", "Tasklist font color", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("Dialog", "Selected Item background", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("Dialog", "Text input background", None, QtGui.QApplication.UnicodeUTF8))
        self.resetToDefaults.setText(QtGui.QApplication.translate("Dialog", " Reset to default settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("Dialog", "Tasklist Font size", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.themeTab), QtGui.QApplication.translate("Dialog", " Theme ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("Dialog", "Toggle main window", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.shortcutsTab), QtGui.QApplication.translate("Dialog", " Shortcuts ", None, QtGui.QApplication.UnicodeUTF8))

