# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created: Wed Nov 19 13:07:44 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(478, 288)
        Dialog.setModal(False)
        self.gridLayout_3 = QtGui.QGridLayout(Dialog)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_3.addWidget(self.buttonBox, 2, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.generalTab = QtGui.QWidget()
        self.generalTab.setObjectName("generalTab")
        self.formLayout = QtGui.QFormLayout(self.generalTab)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(self.generalTab)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.startupContext = QtGui.QComboBox(self.generalTab)
        self.startupContext.setObjectName("startupContext")
        self.startupContext.addItem("")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.startupContext)
        self.label_2 = QtGui.QLabel(self.generalTab)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.dateFormat = QtGui.QLineEdit(self.generalTab)
        self.dateFormat.setObjectName("dateFormat")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.dateFormat)
        self.label_3 = QtGui.QLabel(self.generalTab)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_3)
        self.confirmExit = QtGui.QCheckBox(self.generalTab)
        self.confirmExit.setChecked(True)
        self.confirmExit.setObjectName("confirmExit")
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.confirmExit)
        self.label_7 = QtGui.QLabel(self.generalTab)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_7)
        self.defaultDueTimeOn = QtGui.QCheckBox(self.generalTab)
        self.defaultDueTimeOn.setChecked(True)
        self.defaultDueTimeOn.setObjectName("defaultDueTimeOn")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.defaultDueTimeOn)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.defaultDueTimeSpin = QtGui.QSpinBox(self.generalTab)
        self.defaultDueTimeSpin.setMaximumSize(QtCore.QSize(35, 16777215))
        self.defaultDueTimeSpin.setProperty("value", 24)
        self.defaultDueTimeSpin.setObjectName("defaultDueTimeSpin")
        self.horizontalLayout.addWidget(self.defaultDueTimeSpin)
        self.defaultDueTimeUnit = QtGui.QComboBox(self.generalTab)
        self.defaultDueTimeUnit.setMaximumSize(QtCore.QSize(60, 16777215))
        self.defaultDueTimeUnit.setObjectName("defaultDueTimeUnit")
        self.defaultDueTimeUnit.addItem("")
        self.defaultDueTimeUnit.addItem("")
        self.horizontalLayout.addWidget(self.defaultDueTimeUnit)
        self.label_8 = QtGui.QLabel(self.generalTab)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.formLayout.setLayout(4, QtGui.QFormLayout.FieldRole, self.horizontalLayout)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout.setItem(5, QtGui.QFormLayout.LabelRole, spacerItem)
        self.tabWidget.addTab(self.generalTab, "")
        self.notificationsTab = QtGui.QWidget()
        self.notificationsTab.setObjectName("notificationsTab")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.notificationsTab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.notificationsOn = QtGui.QCheckBox(self.notificationsTab)
        self.notificationsOn.setChecked(True)
        self.notificationsOn.setObjectName("notificationsOn")
        self.gridLayout_2.addWidget(self.notificationsOn, 0, 0, 1, 1)
        self.notificationsCurrentContext = QtGui.QCheckBox(self.notificationsTab)
        self.notificationsCurrentContext.setChecked(True)
        self.notificationsCurrentContext.setObjectName("notificationsCurrentContext")
        self.gridLayout_2.addWidget(self.notificationsCurrentContext, 1, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtGui.QLabel(self.notificationsTab)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.notificationsTab)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.notifyIntervalSpin = QtGui.QSpinBox(self.notificationsTab)
        self.notifyIntervalSpin.setMaximumSize(QtCore.QSize(40, 16777215))
        self.notifyIntervalSpin.setMaximum(60)
        self.notifyIntervalSpin.setProperty("value", 30)
        self.notifyIntervalSpin.setObjectName("notifyIntervalSpin")
        self.gridLayout.addWidget(self.notifyIntervalSpin, 1, 1, 1, 1)
        self.notifyTimeUnit = QtGui.QComboBox(self.notificationsTab)
        self.notifyTimeUnit.setMaximumSize(QtCore.QSize(70, 16777215))
        self.notifyTimeUnit.setObjectName("notifyTimeUnit")
        self.notifyTimeUnit.addItem("")
        self.notifyTimeUnit.addItem("")
        self.gridLayout.addWidget(self.notifyTimeUnit, 0, 2, 1, 1)
        self.notifyTimeSpin = QtGui.QSpinBox(self.notificationsTab)
        self.notifyTimeSpin.setMaximumSize(QtCore.QSize(40, 16777215))
        self.notifyTimeSpin.setProperty("value", 6)
        self.notifyTimeSpin.setObjectName("notifyTimeSpin")
        self.gridLayout.addWidget(self.notifyTimeSpin, 0, 1, 1, 1)
        self.notifyIntervalUnit = QtGui.QComboBox(self.notificationsTab)
        self.notifyIntervalUnit.setMaximumSize(QtCore.QSize(70, 16777215))
        self.notifyIntervalUnit.setObjectName("notifyIntervalUnit")
        self.notifyIntervalUnit.addItem("")
        self.notifyIntervalUnit.addItem("")
        self.gridLayout.addWidget(self.notifyIntervalUnit, 1, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.tabWidget.addTab(self.notificationsTab, "")
        self.fontsTab = QtGui.QWidget()
        self.fontsTab.setObjectName("fontsTab")
        self.gridLayout_5 = QtGui.QGridLayout(self.fontsTab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.allFonts = QtGui.QListWidget(self.fontsTab)
        self.allFonts.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.allFonts.setObjectName("allFonts")
        self.horizontalLayout_12.addWidget(self.allFonts)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setContentsMargins(3, -1, 3, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.addFonts = QtGui.QPushButton(self.fontsTab)
        self.addFonts.setMaximumSize(QtCore.QSize(14, 50))
        self.addFonts.setObjectName("addFonts")
        self.verticalLayout.addWidget(self.addFonts)
        self.removeFonts = QtGui.QPushButton(self.fontsTab)
        self.removeFonts.setMaximumSize(QtCore.QSize(14, 50))
        self.removeFonts.setObjectName("removeFonts")
        self.verticalLayout.addWidget(self.removeFonts)
        self.horizontalLayout_12.addLayout(self.verticalLayout)
        self.chosenFonts = QtGui.QListWidget(self.fontsTab)
        self.chosenFonts.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.chosenFonts.setObjectName("chosenFonts")
        self.horizontalLayout_12.addWidget(self.chosenFonts)
        self.gridLayout_5.addLayout(self.horizontalLayout_12, 1, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.fontsTab)
        self.label_13.setObjectName("label_13")
        self.gridLayout_5.addWidget(self.label_13, 0, 0, 1, 1)
        self.tabWidget.addTab(self.fontsTab, "")
        self.themeTab = QtGui.QWidget()
        self.themeTab.setObjectName("themeTab")
        self.gridLayout_4 = QtGui.QGridLayout(self.themeTab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_9 = QtGui.QLabel(self.themeTab)
        self.label_9.setMaximumSize(QtCore.QSize(158, 16777215))
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        self.windowFrame = QtGui.QPushButton(self.themeTab)
        self.windowFrame.setMaximumSize(QtCore.QSize(20, 20))
        self.windowFrame.setAutoFillBackground(True)
        self.windowFrame.setText("")
        self.windowFrame.setFlat(False)
        self.windowFrame.setObjectName("windowFrame")
        self.horizontalLayout_4.addWidget(self.windowFrame)
        self.gridLayout_4.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_16 = QtGui.QLabel(self.themeTab)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_8.addWidget(self.label_16)
        self.taskEditorOpacity = QtGui.QSpinBox(self.themeTab)
        self.taskEditorOpacity.setMaximumSize(QtCore.QSize(35, 16777215))
        self.taskEditorOpacity.setMaximum(100)
        self.taskEditorOpacity.setSingleStep(5)
        self.taskEditorOpacity.setProperty("value", 90)
        self.taskEditorOpacity.setObjectName("taskEditorOpacity")
        self.horizontalLayout_8.addWidget(self.taskEditorOpacity)
        self.gridLayout_4.addLayout(self.horizontalLayout_8, 1, 1, 1, 1)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_14 = QtGui.QLabel(self.themeTab)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_10.addWidget(self.label_14)
        self.taskEditorBG = QtGui.QPushButton(self.themeTab)
        self.taskEditorBG.setMaximumSize(QtCore.QSize(20, 20))
        self.taskEditorBG.setAutoFillBackground(True)
        self.taskEditorBG.setText("")
        self.taskEditorBG.setFlat(False)
        self.taskEditorBG.setObjectName("taskEditorBG")
        self.horizontalLayout_10.addWidget(self.taskEditorBG)
        self.gridLayout_4.addLayout(self.horizontalLayout_10, 0, 1, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtGui.QLabel(self.themeTab)
        self.label_6.setMaximumSize(QtCore.QSize(158, 16777215))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.windowBG = QtGui.QPushButton(self.themeTab)
        self.windowBG.setMaximumSize(QtCore.QSize(20, 20))
        self.windowBG.setAutoFillBackground(True)
        self.windowBG.setText("")
        self.windowBG.setFlat(False)
        self.windowBG.setObjectName("windowBG")
        self.horizontalLayout_3.addWidget(self.windowBG)
        self.gridLayout_4.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_11 = QtGui.QLabel(self.themeTab)
        self.label_11.setMaximumSize(QtCore.QSize(158, 16777215))
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_6.addWidget(self.label_11)
        self.tasklistFrame = QtGui.QPushButton(self.themeTab)
        self.tasklistFrame.setMaximumSize(QtCore.QSize(20, 20))
        self.tasklistFrame.setAutoFillBackground(True)
        self.tasklistFrame.setText("")
        self.tasklistFrame.setFlat(False)
        self.tasklistFrame.setObjectName("tasklistFrame")
        self.horizontalLayout_6.addWidget(self.tasklistFrame)
        self.gridLayout_4.addLayout(self.horizontalLayout_6, 3, 0, 1, 1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_15 = QtGui.QLabel(self.themeTab)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_9.addWidget(self.label_15)
        self.tasklistFontSize = QtGui.QSpinBox(self.themeTab)
        self.tasklistFontSize.setMaximumSize(QtCore.QSize(35, 16777215))
        self.tasklistFontSize.setMinimum(8)
        self.tasklistFontSize.setMaximum(24)
        self.tasklistFontSize.setProperty("value", 10)
        self.tasklistFontSize.setObjectName("tasklistFontSize")
        self.horizontalLayout_9.addWidget(self.tasklistFontSize)
        self.gridLayout_4.addLayout(self.horizontalLayout_9, 5, 1, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_12 = QtGui.QLabel(self.themeTab)
        self.label_12.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_2.addWidget(self.label_12)
        self.tasklistFont = QtGui.QComboBox(self.themeTab)
        self.tasklistFont.setObjectName("tasklistFont")
        self.horizontalLayout_2.addWidget(self.tasklistFont)
        self.gridLayout_4.addLayout(self.horizontalLayout_2, 5, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_10 = QtGui.QLabel(self.themeTab)
        self.label_10.setMaximumSize(QtCore.QSize(158, 16777215))
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_5.addWidget(self.label_10)
        self.tasklistBG = QtGui.QPushButton(self.themeTab)
        self.tasklistBG.setMaximumSize(QtCore.QSize(20, 20))
        self.tasklistBG.setAutoFillBackground(True)
        self.tasklistBG.setText("")
        self.tasklistBG.setFlat(False)
        self.tasklistBG.setObjectName("tasklistBG")
        self.horizontalLayout_5.addWidget(self.tasklistBG)
        self.gridLayout_4.addLayout(self.horizontalLayout_5, 2, 0, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_17 = QtGui.QLabel(self.themeTab)
        self.label_17.setMaximumSize(QtCore.QSize(158, 16777215))
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_7.addWidget(self.label_17)
        self.tasklistFontColor = QtGui.QPushButton(self.themeTab)
        self.tasklistFontColor.setMaximumSize(QtCore.QSize(20, 20))
        self.tasklistFontColor.setAutoFillBackground(True)
        self.tasklistFontColor.setText("")
        self.tasklistFontColor.setFlat(False)
        self.tasklistFontColor.setObjectName("tasklistFontColor")
        self.horizontalLayout_7.addWidget(self.tasklistFontColor)
        self.gridLayout_4.addLayout(self.horizontalLayout_7, 4, 0, 1, 1)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_18 = QtGui.QLabel(self.themeTab)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_11.addWidget(self.label_18)
        self.windowOpacity = QtGui.QSpinBox(self.themeTab)
        self.windowOpacity.setMaximumSize(QtCore.QSize(35, 16777215))
        self.windowOpacity.setMaximum(100)
        self.windowOpacity.setSingleStep(5)
        self.windowOpacity.setProperty("value", 90)
        self.windowOpacity.setObjectName("windowOpacity")
        self.horizontalLayout_11.addWidget(self.windowOpacity)
        self.gridLayout_4.addLayout(self.horizontalLayout_11, 2, 1, 1, 1)
        self.diableModality = QtGui.QCheckBox(self.themeTab)
        self.diableModality.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.diableModality.setObjectName("diableModality")
        self.gridLayout_4.addWidget(self.diableModality, 4, 1, 1, 1)
        self.tabWidget.addTab(self.themeTab, "")
        self.shortcutsTab = QtGui.QWidget()
        self.shortcutsTab.setObjectName("shortcutsTab")
        self.formLayout_2 = QtGui.QFormLayout(self.shortcutsTab)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_19 = QtGui.QLabel(self.shortcutsTab)
        self.label_19.setObjectName("label_19")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_19)
        self.mainWindowToggleKey = QtGui.QLineEdit(self.shortcutsTab)
        self.mainWindowToggleKey.setCursor(QtCore.Qt.IBeamCursor)
        self.mainWindowToggleKey.setObjectName("mainWindowToggleKey")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.mainWindowToggleKey)
        self.tabWidget.addTab(self.shortcutsTab, "")
        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        self.notifyIntervalUnit.setCurrentIndex(1)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "workload settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Startup context", None, QtGui.QApplication.UnicodeUTF8))
        self.startupContext.setItemText(0, QtGui.QApplication.translate("Dialog", "Last opened", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Date and time format", None, QtGui.QApplication.UnicodeUTF8))
        self.dateFormat.setText(QtGui.QApplication.translate("Dialog", "%d-%m-%Y %H:%M", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "On program exit", None, QtGui.QApplication.UnicodeUTF8))
        self.confirmExit.setText(QtGui.QApplication.translate("Dialog", "Confirm exit", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "New tasks:", None, QtGui.QApplication.UnicodeUTF8))
        self.defaultDueTimeOn.setText(QtGui.QApplication.translate("Dialog", "Set default due date/time", None, QtGui.QApplication.UnicodeUTF8))
        self.defaultDueTimeUnit.setItemText(0, QtGui.QApplication.translate("Dialog", "Hour(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.defaultDueTimeUnit.setItemText(1, QtGui.QApplication.translate("Dialog", "Day(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", " after create time", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.generalTab), QtGui.QApplication.translate("Dialog", "General", None, QtGui.QApplication.UnicodeUTF8))
        self.notificationsOn.setText(QtGui.QApplication.translate("Dialog", "Show notifications", None, QtGui.QApplication.UnicodeUTF8))
        self.notificationsCurrentContext.setText(QtGui.QApplication.translate("Dialog", "Only from current context", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Repeat notification every:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Notify about ending task (before task end):", None, QtGui.QApplication.UnicodeUTF8))
        self.notifyTimeUnit.setItemText(0, QtGui.QApplication.translate("Dialog", "Hour(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.notifyTimeUnit.setItemText(1, QtGui.QApplication.translate("Dialog", "Minute(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.notifyIntervalUnit.setItemText(0, QtGui.QApplication.translate("Dialog", "Hour(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.notifyIntervalUnit.setItemText(1, QtGui.QApplication.translate("Dialog", "Minute(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.notificationsTab), QtGui.QApplication.translate("Dialog", "Notifications", None, QtGui.QApplication.UnicodeUTF8))
        self.addFonts.setText(QtGui.QApplication.translate("Dialog", ">", None, QtGui.QApplication.UnicodeUTF8))
        self.removeFonts.setText(QtGui.QApplication.translate("Dialog", "<", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Dialog", "Select Fonts you would like to use in program", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.fontsTab), QtGui.QApplication.translate("Dialog", "Fonts", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "Window frame", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Dialog", "Task editor opacity", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Dialog", "Task editor Background", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Window background", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Dialog", "Tasklist frame", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Dialog", "Tasklist font size", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Dialog", "Tasklist font", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog", "Tasklist background", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Dialog", "Tasklist font color", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Dialog", "Main window opacity", None, QtGui.QApplication.UnicodeUTF8))
        self.diableModality.setText(QtGui.QApplication.translate("Dialog", "Enable Window Modality", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.themeTab), QtGui.QApplication.translate("Dialog", "Theme", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("Dialog", "Toggle main window", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.shortcutsTab), QtGui.QApplication.translate("Dialog", "Shortcuts", None, QtGui.QApplication.UnicodeUTF8))

