# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'task.ui'
#
# Created: Mon Nov  3 14:07:22 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(517, 523)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.priorityText = QtGui.QLabel(self.groupBox_2)
        self.priorityText.setObjectName("priorityText")
        self.gridLayout.addWidget(self.priorityText, 1, 4, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.dueDate = QtGui.QDateTimeEdit(self.groupBox_2)
        self.dueDate.setCalendarPopup(True)
        self.dueDate.setObjectName("dueDate")
        self.gridLayout.addWidget(self.dueDate, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 2, 1, 1)
        self.priority = QtGui.QSpinBox(self.groupBox_2)
        self.priority.setMinimumSize(QtCore.QSize(20, 0))
        self.priority.setMaximumSize(QtCore.QSize(35, 16777215))
        self.priority.setMaximum(5)
        self.priority.setObjectName("priority")
        self.gridLayout.addWidget(self.priority, 1, 3, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.createDate = QtGui.QLabel(self.groupBox_2)
        self.createDate.setText("")
        self.createDate.setObjectName("createDate")
        self.gridLayout.addWidget(self.createDate, 0, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 2, 1, 1)
        self.closeDate = QtGui.QLabel(self.groupBox_2)
        self.closeDate.setText("")
        self.closeDate.setObjectName("closeDate")
        self.gridLayout.addWidget(self.closeDate, 0, 3, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 5, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.taskName = QtGui.QLineEdit(Dialog)
        self.taskName.setObjectName("taskName")
        self.gridLayout_3.addWidget(self.taskName, 0, 1, 1, 1)
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.frame = QtGui.QFrame(Dialog)
        self.frame.setMinimumSize(QtCore.QSize(0, 22))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 39))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_4 = QtGui.QGridLayout(self.frame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.editorItalic = QtGui.QPushButton(self.frame)
        self.editorItalic.setMaximumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setItalic(True)
        self.editorItalic.setFont(font)
        self.editorItalic.setObjectName("editorItalic")
        self.gridLayout_4.addWidget(self.editorItalic, 0, 1, 1, 1)
        self.editorUnderline = QtGui.QPushButton(self.frame)
        self.editorUnderline.setMaximumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.editorUnderline.setFont(font)
        self.editorUnderline.setObjectName("editorUnderline")
        self.gridLayout_4.addWidget(self.editorUnderline, 0, 2, 1, 1)
        self.editorBold = QtGui.QPushButton(self.frame)
        self.editorBold.setMaximumSize(QtCore.QSize(20, 20))
        self.editorBold.setObjectName("editorBold")
        self.gridLayout_4.addWidget(self.editorBold, 0, 0, 1, 1)
        self.pushButton_5 = QtGui.QPushButton(self.frame)
        self.pushButton_5.setMaximumSize(QtCore.QSize(55, 20))
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_4.addWidget(self.pushButton_5, 0, 4, 1, 1)
        self.pushButton_4 = QtGui.QPushButton(self.frame)
        self.pushButton_4.setMaximumSize(QtCore.QSize(55, 20))
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_4.addWidget(self.pushButton_4, 0, 3, 1, 1)
        self.fontComboBox = QtGui.QFontComboBox(self.frame)
        self.fontComboBox.setMaximumSize(QtCore.QSize(16777215, 20))
        self.fontComboBox.setObjectName("fontComboBox")
        self.gridLayout_4.addWidget(self.fontComboBox, 0, 5, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 0, 6, 1, 1)
        self.verticalLayout.addWidget(self.frame)
        self.taskDescription = QtGui.QTextEdit(Dialog)
        self.taskDescription.setObjectName("taskDescription")
        self.verticalLayout.addWidget(self.taskDescription)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setMaximumSize(QtCore.QSize(16777215, 22))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.priorityText.setText(QtGui.QApplication.translate("Dialog", "Now", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Due", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Priority", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Created:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Closed:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Task Name: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Task Description", None, QtGui.QApplication.UnicodeUTF8))
        self.editorItalic.setText(QtGui.QApplication.translate("Dialog", "I", None, QtGui.QApplication.UnicodeUTF8))
        self.editorUnderline.setText(QtGui.QApplication.translate("Dialog", "U", None, QtGui.QApplication.UnicodeUTF8))
        self.editorBold.setText(QtGui.QApplication.translate("Dialog", "B", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_5.setText(QtGui.QApplication.translate("Dialog", "text color", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_4.setText(QtGui.QApplication.translate("Dialog", "bg color", None, QtGui.QApplication.UnicodeUTF8))

